import yargs, { CommandModule, type ArgumentsCamelCase } from "yargs";
import { simpleGit } from "simple-git";
import * as fs from "fs-extra";
import * as path from "path";
import os from "os";
import ora from "ora";
import chalk from "chalk";
import prompts from "prompts";
import { getGit } from "../../lib/git.js";
import { argv } from "process";
import { handleError } from "../../utils/errors.js";

interface StartArgs {
  name: string;
  template: string;
}

export const startCommand: CommandModule<{}, StartArgs> = {
  command: "start <name>",
  describe: "Create a new workspace for Git Grinder",

  builder: (yargs) => {
    return yargs
      .positional("name", {
        type: "string",
        description: "Name of the project",
        demandOption: true,
      })
      .option("template", {
        alias: "t",
        describe: "Pre-select a stack (node, python, go)",
        type: "string",
        choices: ["node", "python", "go", "none"],
        default: "none",
      })
      .example(
        "$0 start my-project -t node",
        "Create a new Node.js workspace called my-project"
      );
  },

  handler: async (argv: ArgumentsCamelCase<StartArgs>) => {
    const git = getGit();
    const spinner = ora();

    try {
      const projectName = argv.name;
      const targetPath = path.join(process.cwd(), projectName);
      if (fs.existsSync(targetPath)) {
        console.log(
          chalk.red(`Directory ${projectName} already exists. Aborting.`)
        );
        process.exit(1);
      }
      console.log(chalk.green(`Creating new project: ${projectName}`));

      // make directory and initialise git
      fs.ensureDirSync(targetPath);
      await git.init(["--initial-branch=main"]);

      // handle template
      let stack: string = argv.template;
      if (!stack) {
        const response = await prompts({
          type: "select",
          name: "value",
          message: "Select your stack (for .gitignore):",
          choices: [
            { title: "Node/JS/TS", value: "node" },
            { title: "Python", value: "python" },
            { title: "Go", value: "go" },
            { title: "None (Empty)", value: "none" },
          ],
        });
        stack = response.value;
      }

      // write files
      const templates: Record<string, string> = {
        node: "node_modules/\n.env\n.DS_Store\ndist/\ncoverage/",
        python: "__pycache__/\nvenv/\n.env\n*.pyc",
        go: "/bin\n.env",
        none: ".env\n.DS_Store",
      };

      const gitIgnoreContent = templates[stack] || templates["none"];
      // FIXME: gitIgnoreContent need to not be undefined
      gitIgnoreContent &&
        fs.writeFileSync(path.join(targetPath, ".gitignore"), gitIgnoreContent);
      gitIgnoreContent &&
        fs.writeFileSync(
          path.join(targetPath, "README.md"),
          `# ${projectName}\n\nGenerated by Git Grinder.\n`
        );

      //   make first commit
      await git.add(".");
      await git.commit("Initial commit");

      console.log(
        chalk.green(
          `Project ${projectName} created successfully at ${targetPath}`
        )
      );
    } catch (error) {
      spinner.fail(chalk.red("Failed to create new workspace."));
      handleError(error);
    }
  },
};
